---
- name: test
  hosts: all
  remote_user: root
  
  tasks:
  
# обновить кеш репозиториев
  - name: Update apt-get repo and cache
    apt: 
      update_cache: yes                    
      force_apt_get: yes 
      cache_valid_time: 3600

# обновление всех пакетов  
  - name: Upgrade all apt packages
    apt:
      upgrade: dist
      force_apt_get: yes

...
   